[package]
name = "mdm-core"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hwp2mdm"
path = "src/main.rs"

[dependencies]
cfb = "0.12.1"
flate2 = "1.0"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
encoding_rs = "0.8"
